<?php

namespace Gobie\Debug\Highlighters;

use Gobie\Debug\Debug;

/**
 * Zvýrazňovač syntaxe.
 */
class NativeHighlighter implements IHighlighter
{

    const
        PATTERN_REMOVE_INDENTATION = 1,
        PATTERN_HIGHLIGHT = 2,
        PATTERN_TABLE_LINKS = 4,
        PATTERN_ALL = 7;

    /**
     * Mapa typu databází a jejich klíčových slov.
     *
     * @var array
     */
    protected static $keywords = array(
        'mysql'  => 'ADD|ALL|ALTER|ANALYZE|AND|ASC|ASENSITIVE|AS|BEFORE|BETWEEN|BIGINT|BINARY|BLOB|BOTH|BY|CALL|CASCADE|CASE|CHANGE|CHARACTER|CHAR|CHECK|COLLATE|COLUMN|CONDITION|CONSTRAINT|CONTINUE|CONVERT|CREATE|CROSS|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASES|DATABASE|DAY_HOUR|DAY_MICROSECOND|DAY_MINUTE|DAY_SECOND|DEC|DECIMAL|DECLARE|DEFAULT|DELAYED|DELETE|DESCRIBE|DESC|DETERMINISTIC|DISTINCTROW|DISTINCT|DIV|DOUBLE|DROP|DUAL|EACH|ELSEIF|ELSE|ENCLOSED|ESCAPED|EXISTS|EXIT|EXPLAIN|FALSE|FETCH|FLOAT4|FLOAT8|FLOAT|FORCE|FOREIGN|FOR|FROM|FULLTEXT|GRANT|GROUP|HAVING|HIGH_PRIORITY|HOUR_MICROSECOND|HOUR_MINUTE|HOUR_SECOND|IF|IGNORE|INDEX|INFILE|INNER|INOUT|INSENSITIVE|INSERT|INT1|INT2|INT3|INT4|INT8|INTEGER|INTERVAL|INTO|INT|IN|IS|ITERATE|JOIN|KEYS|KEY|KILL|LEADING|LEAVE|LEFT|LIKE|LIMIT|LINES|LOAD|LOCALTIME|LOCALTIMESTAMP|LOCK|LONGBLOB|LONGTEXT|LONG|LOOP|LOW_PRIORITY|MATCH|MEDIUMBLOB|MEDIUMINT|MEDIUMTEXT|MIDDLEINT|MINUTE_MICROSECOND|MINUTE_SECOND|MODIFIES|MOD|NATURAL|NOT|NO_WRITE_TO_BINLOG|NULL|NUMERIC|ON|OPTIMIZE|OPTION|OPTIONALLY|ORDER|OR|OUTER|OUTFILE|OUT|PRECISION|PRIMARY|PROCEDURE|PURGE|READS|READ|REAL|REFERENCES|REGEXP|RELEASE|RENAME|REPEAT|REPLACE|REQUIRE|RESTRICT|RETURN|REVOKE|RIGHT|RLIKE|SCHEMAS|SCHEMA|SECOND_MICROSECOND|SELECT|SENSITIVE|SEPARATOR|SET|SHOW|SMALLINT|SONAME|SPATIAL|SPECIFIC|SQLEXCEPTION|SQLSTATE|SQLWARNING|SQL_BIG_RESULT|SQL_CALC_FOUND_ROWS|SQL_SMALL_RESULT|SQL|SSL|STARTING|STRAIGHT_JOIN|TABLE|TERMINATED|THEN|TINYBLOB|TINYINT|TINYTEXT|TO|TRAILING|TRIGGER|TRUE|UNDO|UNION|UNIQUE|UNLOCK|UNSIGNED|UPDATE|USAGE|USE|USING|UTC_DATE|UTC_TIME|UTC_TIMESTAMP|VALUES|VARBINARY|VARCHAR|VARCHARACTER|VARYING|WHEN|WHERE|WHILE|WITH|WRITE|XOR|YEAR_MONTH|ZEROFILL|ASENSITIVE|CALL|CONDITION|CONNECTION|CONTINUE|CURSOR|DECLARE|DETERMINISTIC|EACH|ELSEIF|EXIT|FETCH|GOTO|INOUT|INSENSITIVE|ITERATE|LABEL|LEAVE|LOOP|MODIFIES|OUT|READS|RELEASE|REPEAT|RETURN|SCHEMA|SCHEMAS|SENSITIVE|SPECIFIC|SQL|SQLEXCEPTION|SQLSTATE|SQLWARNING|TRIGGER|UNDO|UPGRADE|WHILE',
        'sqlite' => 'ABORT|ACTION|ADD|AFTER|ALL|ALTER|ANALYZE|AND|AS|ASC|ATTACH|AUTOINCREMENT|BEFORE|BEGIN|BETWEEN|BY|CASCADE|CASE|CAST|CHECK|COLLATE|COLUMN|COMMIT|CONFLICT|CONSTRAINT|CREATE|CROSS|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|DATABASE|DEFAULT|DEFERRABLE|DEFERRED|DELETE|DESC|DETACH|DISTINCT|DROP|EACH|ELSE|END|ESCAPE|EXCEPT|EXCLUSIVE|EXISTS|EXPLAIN|FAIL|FOR|FOREIGN|FROM|FULL|GLOB|GROUP|HAVING|IF|IGNORE|IMMEDIATE|IN|INDEX|INDEXED|INITIALLY|INNER|INSERT|INSTEAD|INTERSECT|INTO|IS|ISNULL|JOIN|KEY|LEFT|LIKE|LIMIT|MATCH|NATURAL|NO|NOT|NOTNULL|NULL|OF|OFFSET|ON|OR|ORDER|OUTER|PLAN|PRAGMA|PRIMARY|QUERY|RAISE|REFERENCES|REGEXP|REINDEX|RELEASE|RENAME|REPLACE|RESTRICT|RIGHT|ROLLBACK|ROW|SAVEPOINT|SELECT|SET|TABLE|TEMP|TEMPORARY|THEN|TO|TRANSACTION|TRIGGER|UNION|UNIQUE|UPDATE|USING|VACUUM|VALUES|VIEW|VIRTUAL|WHEN|WHERE',
        'odbc'   => 'ABSOLUTE|EXEC|OVERLAPS|ACTION|EXECUTE|PAD|ADA|EXISTS|PARTIAL|ADD|EXTERNAL|PASCAL|ALL|EXTRACT|POSITION|ALLOCATE|FALSE|PRECISION|ALTER|FETCH|PREPARE|AND|FIRST|PRESERVE|ANY|FLOAT|PRIMARY|ARE|FOR|PRIOR|AS|FOREIGN|PRIVILEGES|ASC|FORTRAN|PROCEDURE|ASSERTION|FOUND|PUBLIC|AT|FROM|READ|AUTHORIZATION|FULL|REAL|AVG|GET|REFERENCES|BEGIN|GLOBAL|RELATIVE|BETWEEN|GO|RESTRICT|BIT|GOTO|REVOKE|BIT_LENGTH|GRANT|RIGHT|BOTH|GROUP|ROLLBACK|BY|HAVING|ROWS|CASCADE|HOUR|SCHEMA|CASCADED|IDENTITY|SCROLL|CASE|IMMEDIATE|SECOND|CAST|IN|SECTION|CATALOG|INCLUDE|SELECT|CHAR|INDEX|SESSION|CHAR_LENGTH|INDICATOR|SESSION_USER|CHARACTER|INITIALLY|SET|CHARACTER_LENGTH|INNER|SIZE|CHECK|INPUT|SMALLINT|CLOSE|INSENSITIVE|SOME|COALESCE|INSERT|SPACE|COLLATE|INT|SQL|COLLATION|INTEGER|SQLCA|COLUMN|INTERSECT|SQLCODE|COMMIT|INTERVAL|SQLERROR|CONNECT|INTO|SQLSTATE|CONNECTION|IS|SQLWARNING|CONSTRAINT|ISOLATION|SUBSTRING|CONSTRAINTS|JOIN|SUM|CONTINUE|KEY|SYSTEM_USER|CONVERT|LANGUAGE|TABLE|CORRESPONDING|LAST|TEMPORARY|COUNT|LEADING|THEN|CREATE|LEFT|TIME|CROSS|LEVEL|TIMESTAMP|CURRENT|LIKE|TIMEZONE_HOUR|CURRENT_DATE|LOCAL|TIMEZONE_MINUTE|CURRENT_TIME|LOWER|TO|CURRENT_TIMESTAMP|MATCH|TRAILING|CURRENT_USER|MAX|TRANSACTION|CURSOR|MIN|TRANSLATE|DATE|MINUTE|TRANSLATION|DAY|MODULE|TRIM|DEALLOCATE|MONTH|TRUE|DEC|NAMES|UNION|DECIMAL|NATIONAL|UNIQUE|DECLARE|NATURAL|UNKNOWN|DEFAULT|NCHAR|UPDATE|DEFERRABLE|NEXT|UPPER|DEFERRED|NO|USAGE|DELETE|NONE|USER|DESC|NOT|USING|DESCRIBE|NULL|VALUE|DESCRIPTOR|NULLIF|VALUES|DIAGNOSTICS|NUMERIC|VARCHAR|DISCONNECT|OCTET_LENGTH|VARYING|DISTINCT|OF|VIEW|DOMAIN|ON|WHEN|DOUBLE|ONLY|WHENEVER|DROP|OPEN|WHERE|ELSE|OPTION|WITH|END|OR|WORK|END-EXEC|ORDER|WRITE|ESCAPE|OUTER|YEAR|EXCEPT|OUTPUT|ZONE|EXCEPTION',
        'oracle' => 'ADD|ALL|ALTER|ANALYZE|AND|ASC|ASENSITIVE|AS|BEFORE|BETWEEN|BIGINT|BINARY|BLOB|BOTH|BY|CALL|CASCADE|CASE|CHANGE|CHARACTER|CHAR|CHECK|COLLATE|COLUMN|CONDITION|CONSTRAINT|CONTINUE|CONVERT|CREATE|CROSS|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASES|DATABASE|DAY_HOUR|DAY_MICROSECOND|DAY_MINUTE|DAY_SECOND|DEC|DECIMAL|DECLARE|DEFAULT|DELAYED|DELETE|DESCRIBE|DESC|DETERMINISTIC|DISTINCTROW|DISTINCT|DIV|DOUBLE|DROP|DUAL|EACH|ELSEIF|ELSE|ENCLOSED|ESCAPED|EXISTS|EXIT|EXPLAIN|FALSE|FETCH|FLOAT4|FLOAT8|FLOAT|FORCE|FOREIGN|FOR|FROM|FULLTEXT|GRANT|GROUP|HAVING|HIGH_PRIORITY|HOUR_MICROSECOND|HOUR_MINUTE|HOUR_SECOND|IF|IGNORE|INDEX|INFILE|INNER|INOUT|INSENSITIVE|INSERT|INT1|INT2|INT3|INT4|INT8|INTEGER|INTERVAL|INTO|INT|IN|IS|ITERATE|JOIN|KEYS|KEY|KILL|LEADING|LEAVE|LEFT|LIKE|LIMIT|LINES|LOAD|LOCALTIME|LOCALTIMESTAMP|LOCK|LONGBLOB|LONGTEXT|LONG|LOOP|LOW_PRIORITY|MATCH|MEDIUMBLOB|MEDIUMINT|MEDIUMTEXT|MIDDLEINT|MINUTE_MICROSECOND|MINUTE_SECOND|MODIFIES|MOD|NATURAL|NOT|NO_WRITE_TO_BINLOG|NULL|NUMERIC|ON|OPTIMIZE|OPTION|OPTIONALLY|ORDER|OR|OUTER|OUTFILE|OUT|PRECISION|PRIMARY|PROCEDURE|PURGE|READS|READ|REAL|REFERENCES|REGEXP|RELEASE|RENAME|REPEAT|REPLACE|REQUIRE|RESTRICT|RETURN|REVOKE|RIGHT|RLIKE|SCHEMAS|SCHEMA|SECOND_MICROSECOND|SELECT|SENSITIVE|SEPARATOR|SET|SHOW|SMALLINT|SONAME|SPATIAL|SPECIFIC|SQLEXCEPTION|SQLSTATE|SQLWARNING|SQL_BIG_RESULT|SQL_CALC_FOUND_ROWS|SQL_SMALL_RESULT|SQL|SSL|STARTING|STRAIGHT_JOIN|TABLE|TERMINATED|THEN|TINYBLOB|TINYINT|TINYTEXT|TO|TRAILING|TRIGGER|TRUE|UNDO|UNION|UNIQUE|UNLOCK|UNSIGNED|UPDATE|USAGE|USE|USING|UTC_DATE|UTC_TIME|UTC_TIMESTAMP|VALUES|VARBINARY|VARCHAR|VARCHARACTER|VARYING|WHEN|WHERE|WHILE|WITH|WRITE|XOR|YEAR_MONTH|ZEROFILL|ASENSITIVE|CALL|CONDITION|CONNECTION|CONTINUE|CURSOR|DECLARE|DETERMINISTIC|EACH|ELSEIF|EXIT|FETCH|GOTO|INOUT|INSENSITIVE|ITERATE|LABEL|LEAVE|LOOP|MODIFIES|OUT|READS|RELEASE|REPEAT|RETURN|SCHEMA|SCHEMAS|SENSITIVE|SPECIFIC|SQL|SQLEXCEPTION|SQLSTATE|SQLWARNING|TRIGGER|UNDO|UPGRADE|WHILE'
    );

    /**
     * Seznam vzorů a jejich mapování pro zvýraznění syntaxe.
     *
     * @var array
     */
    private $replacePatterns = array();

    /**
     * Typ databáze.
     *
     * @var string
     */
    private $databaseType;

    /**
     * Nastavení databázového spojení.
     *
     * @param Debug   $debug           Debug
     * @param string  $databaseType    Typ databáze
     * @param integer $replacePatterns Mapa vzorů pro nahrazení
     */
    public function __construct(Debug $debug, $databaseType, $replacePatterns = self::PATTERN_ALL)
    {
        $this->databaseType = $databaseType;

        // Clear custom formatting
        if ((self::PATTERN_REMOVE_INDENTATION & $replacePatterns) === self::PATTERN_REMOVE_INDENTATION) {
            $this->replacePatterns[] = array('/\s*\n\s*/imS', "\n");
        }

        // Highlight keywords
        if ((self::PATTERN_HIGHLIGHT & $replacePatterns) === self::PATTERN_HIGHLIGHT) {
            $this->replacePatterns[] = array(
                '/((?:(?:^|\s)(?:%keywords%))+)($|\s|\()/imS',
                "<span class='sql_keyword'>\\1</span>\\2"
            );
        }

        // Make links of tables
        if ((self::PATTERN_TABLE_LINKS & $replacePatterns) === self::PATTERN_TABLE_LINKS) {
            $this->replacePatterns[] = array(
                '/((?:FROM|JOIN)<\/b>)\s+(\w+)/imS',
                "\\1 <a href='" . $debug->replaceLinkParam('table', '\\2') . "' target='_blank'>\\2</a>"
            );
        }
    }

    /**
     * {@inheritdoc}
     * @throws \RuntimeException Pokud dojde k chybě při nahrazování v preg_replace.
     */
    public function highlight($sql)
    {
        if (!isset(self::$keywords[$this->databaseType])) {
            return $sql;
        }

        $keywords = self::$keywords[$this->databaseType];

        foreach ($this->replacePatterns as $replacePattern) {
            list($pattern, $callback) = array_map(
                function ($el) use ($keywords) {
                    return str_replace("%keywords%", $keywords, $el);
                },
                $replacePattern
            );

            $sql = preg_replace($pattern, $callback, $sql);
            if ($err = preg_last_error()) {
                throw new \RuntimeException($pattern, $err);
            }
        }

        return $sql;
    }
}
